volumes:
  redis_data:
    driver: local
  mysql_log_data:
    driver: local
  mysql_lib_data:
    driver: local
  postgres_data:
    driver: local
  www_data:
    driver: local
  bxtemp_data:
    driver: local
  msmtp_data:
    driver: local
  browscap_data:
    driver: local
  geoip2_data:
    driver: local
  ssl_data:
    driver: local
services:
  memcached:
    image: memcached:1.6.38-alpine
    container_name: dev_memcached
    restart: unless-stopped
    env_file:
      - .env
#    ports:
#      - "11211:11211"
    networks:
      dev:
        aliases:
          - memcached
  redis:
    image: redis:7.2.7-alpine
    container_name: dev_redis
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf
    env_file:
      - .env
#    ports:
#      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./confs/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      dev:
        aliases:
          - redis
  postgres:
    image: postgres:16.8-bookworm
    container_name: dev_postgres
    restart: unless-stopped
    env_file:
      - .env
      - .env_sql
#    ports:
#      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      dev:
        aliases:
          - postgres
  mysql:
    image: bx-percona-server:8.0.41-v1-rhel
    container_name: dev_mysql
    restart: unless-stopped
    env_file:
      - .env
      - .env_sql
#    ports:
#      - "3306:3306"
#      - "33060:33060"
    volumes:
      - mysql_log_data:/var/log/mysql
      - mysql_lib_data:/var/lib/mysql
    cap_add:
      - SYS_NICE
    networks:
      dev:
        aliases:
          - mysql
  php:
    image: bx-php:8.2.28-fpm-v1-alpine
    container_name: dev_php
    restart: unless-stopped
    env_file:
      - .env
      - .env_php
#    ports:
#      - "9000:9000"
    volumes:
      - ./confs/php/etc/:/usr/local/etc/
      - www_data:/opt/www/
      - bxtemp_data:/opt/.bx_temp/
      - msmtp_data:/opt/msmtp/
      - browscap_data:/opt/browscap/
      - geoip2_data:/opt/geoip2/
      - ssl_data:/ssl/
    networks:
      dev:
        aliases:
          - php
  nginx:
    image: bx-nginx:1.26.3-v1-alpine
    container_name: dev_nginx
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8588:80"
      - "8589:443"
    volumes:
      - ./confs/nginx/:/etc/nginx/
      - www_data:/opt/www/
      - bxtemp_data:/opt/.bx_temp/
      - ssl_data:/ssl/
    networks:
      dev:
        aliases:
          - nginx
  push-sub:
    image: bx-push:3.0-v1-alpine
    container_name: dev_push_sub
    restart: unless-stopped
    env_file:
      - .env
      - .env_push
      - .env_push_sub
      - .env_redis
#    ports:
#      - "8010:8010"
    networks:
      dev:
        aliases:
          - push_sub
    depends_on:
      - redis
  push-pub:
    image: bx-push:3.0-v1-alpine
    container_name: dev_push_pub
    restart: unless-stopped
    env_file:
      - .env
      - .env_push
      - .env_push_pub
      - .env_redis
#    ports:
#      - "9010:9010"
    networks:
      dev:
        aliases:
          - push_pub
    depends_on:
      - redis
  sphinx:
    image: bx-sphinx:2.2.11-v1-alpine
    container_name: dev_sphinx
#    ports:
#      - "9306:9306"
#      - "9312:9312"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./confs/sphinx/sphinx.conf:/opt/sphinx/conf/sphinx.conf
    networks:
      dev:
        aliases:
          - sphinx
  cron:
    image: bx-php:8.2.28-fpm-v1-alpine
    container_name: dev_cron
    restart: unless-stopped
    command: crond -f -d 8
    user: root
    env_file:
      - .env
      - .env_php
#    ports:
#      - "9001:9000"
    volumes:
      - ./confs/php/etc/:/usr/local/etc/
      - www_data:/opt/www/
      - bxtemp_data:/opt/.bx_temp/
      - msmtp_data:/opt/msmtp/
      - browscap_data:/opt/browscap/
      - geoip2_data:/opt/geoip2/
    networks:
      dev:
        aliases:
          - cron
    depends_on:
      - php
  ssl:
    image: bx-ssl:1.0-v1-alpine
    container_name: dev_ssl
    restart: unless-stopped
    env_file:
      - .env
      - .env_ssl
    volumes:
      - ssl_data:/ssl/
    networks:
      dev:
        aliases:
          - ssl
    depends_on:
      - nginx
networks:
  dev:
    driver: bridge
    attachable: true
    internal: false
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/24
